name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  security:
    uses: joaohenrique11z/teste_esteira/.github/workflows/pipeline.yml@main
    with:
      project_name: AS-PipesAndFilters-Temp
      stack_type: python
      run_dast: false