name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  security:
    uses: joaohenrique11z/teste_esteira/.github/workflows/pipeline.yml@main
    with:
      project_name: AS-PipesAndFilters-Temp
      stack_type: python
      run_dast: true
      dast_target_url: https://example.com
    secrets:
      DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
      DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}